
trigger:
#- master
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      #name: Default
      #demands: agent.os -equals Linux
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Apt Update and Install of prerequisites
      inputs:
        targetType: inline
        script: |
                sudo apt-get -y update
                sudo apt-get -y upgrade
                

    - task: Docker@2
      displayName: Build an image with numeric tag
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'piotrowsianko/project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
              $(tag)
    - task: Docker@2
      displayName: Build and image with "latest" tag
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'piotrowsianko/project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'