name: Terraform_setup.yml

trigger: none

#This pipeline will be triggerred by another pipeline
resources:
  pipelines:
    - pipeline: Terraform_scripts
      source: Continous Integration (Building application and pushing to dockerhub)
      trigger: true


stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: Start terraform script from main.tf
      pool: 
        #name: Default
        #demands: agent.os -equals Linux
        vmImage: ubuntu-latest
      steps:
      - task: Bash@3
        displayName: Print directory
        inputs:
          targetType: inline
          script: |
                  #! /bin/bash
                  pwd
                  ls -a
      - task: AzureKeyVault@2
        displayName: Connecting to Azure Key Vault
        inputs:
          azureSubscription: 'Azure subscription 1(dfcefdc0-4ded-42a0-933b-100fbb1721ed)'
          KeyVaultName: 'key-vault-gl'
          SecretsFilter: '*'
          RunAsPreJob: true

      - task: Bash@3
        displayName: Upload AWS credentials to machine to startup the AWS
        inputs:
          targetType: inline
          script: |
                  #! /bin/bash
                  export AWS_ACCESS_KEY_ID=$(AWS-ACCESS-KEY-ID)
                  export AWS_SECRET_ACCESS_KEY=$(AWS-SECRET-ACCESS-KEY)
                  export AWS_REGION="us-east-1"


      - task: Bash@3
        displayName: Terraform Scripts
        inputs:
          targetType: inline
          script: |
                  #! /bin/bash
                  cd terraform
                  terraform init
                  terraform apply
