name: Terraform_setup.yml

trigger: none

#This pipeline will be triggerred by another pipeline
#resources:
  #pipelines:
    #- pipeline: Terraform_scripts
      #source: Continous Integration (Building application and pushing to dockerhub)
      #trigger: true


stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: Start terraform script from main.tf
      pool: 
        #name: Default
        #demands: agent.os -equals Linux
        vmImage: ubuntu-latest
      variables:
      - group: "ACCESS-VARIABLES"
      steps:
      - checkout: self
      - task: AzureKeyVault@2
        displayName: Connecting to Azure Key Vault
        inputs:
          azureSubscription: 'Azure subscription 1(dfcefdc0-4ded-42a0-933b-100fbb1721ed)'
          KeyVaultName: 'key-vault-gl'
          SecretsFilter: '*'
          RunAsPreJob: true
      - task: Bash@3
        displayName: Terraform Init
        inputs:
          targetType: 'inline'
          script: |
                  export AWS_ACCESS_KEY_ID=$(AWS-ACCESS-KEY-ID)
                  export AWS_SECRET_ACCESS_KEY=$(AWS-SECRET-ACCESS-KEY)
                  export AWS_REGION="us-east-1"
                  cd terraform
                  terraform init -reconfigure
                  terraform validate
                  terraform apply -auto-approve 
                  az pipelines variable-group variable update --group-id 1 --name ECR_URL_PRODUCTION --value $(terraform output -raw repository_url)
        env:
          AZURE_DEVOPS_EXT_PAT: $(PAT)