pool: New Agent self-hosted

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image with numeric tag
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'piotrowsianko/project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
              $(tag)
    - task: Docker@2
      displayName: Build and image with "latest" tag
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'piotrowsianko/project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'