
trigger:
#- master
- none

resources:
- repo: self

variables:
- group: "ACCESS-VARIABLES"


stages:

- stage: Build
  displayName: Build image
  jobs:
  - job: Job_1
    displayName: Build image to ECR
    pool:
      #name: Default
      #demands: agent.os -equals Linux
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Apt Update and Install of prerequisites
      inputs:
        targetType: inline
        script: |
                sudo apt-get -y update
                sudo apt-get -y upgrade
    - task: Docker@2
      displayName: Build and image with "latest" tag
      inputs:
        containerRegistry: 'docker_1'
        repository: 'piotrowsianko/project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'



          



