name: Terraform_setup.yml

trigger: none

#This pipeline will be triggerred by another pipeline
resources:
  pipelines:
    - pipeline: Terraform_scripts
      source: Continous Integration (Building application and pushing to dockerhub)
      trigger: true



pool: 
  name: Default
  demands: agent.os -equals Linux
  steps:
  - task: Bash@3
    displayName: Terraform Scripts
    inputs:
      targetType: inline
      script: |
              terraform init
              terraform apply
