trigger:
- dev-test
- none

resources:
- repo: self

stages:
- stage: Build_infrastracture
  jobs:
  - job: Build
    displayName: Initialize AWS infrastracture with terraform scripts
    pool: 
      vmImage: ubuntu-latest
    variables:
    - group: "ACCESS-VARIABLES"
    steps:
    - checkout: self
    - task: AzureKeyVault@2
      displayName: Connecting to Azure Key Vault
      inputs:
        azureSubscription: 'Azure subscription 1(dfcefdc0-4ded-42a0-933b-100fbb1721ed)'
        KeyVaultName: 'key-vault-gl'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: Bash@3
      displayName: Authentication to AWS
      inputs:
        targetType: 'inline'
        script: |
                aws configure set aws_access_key_id $(AWS-ACCESS-KEY-ID)
                aws configure set aws_secret_access_key $(AWS-SECRET-ACCESS-KEY)
                aws configure set default.region us-east-1
    - task: Bash@3
      displayName: Push application image to ECR
      inputs:
        targetType: 'inline'
        script: |
                #! /bin/bash
                export db_username=$(db-username-test)
                export db_password=$(db-password-test)
                export db_endpoint=$(db-testing-endpoint)
                docker build -t production .
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(ECR_URL_PRODUCTION)
                docker tag testing:$(Build.BuildNumber) $(ECR_URL_TESTING)
                docker push $(ECR_URL_TESTING)
                docker tag testing:latest $(ECR_URL_TESTING)
                docker push $(ECR_URL_TESTING)
