name: 1.$(Rev:r)
trigger:
- feature*


resources:
- repo: self

stages:
- stage: Build_infrastracture
  jobs:
  - job: Build
    displayName: Build, test and push app image to ECR-testing
    pool: 
      vmImage: ubuntu-latest
    variables:
    - group: "ACCESS-VARIABLES"
    steps:
    - checkout: self
    - task: AzureKeyVault@2
      displayName: Connecting to Azure Key Vault
      inputs:
        azureSubscription: 'Azure subscription 1(dfcefdc0-4ded-42a0-933b-100fbb1721ed)'
        KeyVaultName: 'key-vault-gl'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: Bash@3
      displayName: Authentication to AWS
      inputs:
        targetType: 'inline'
        script: |
                aws configure set aws_access_key_id $(AWS-ACCESS-KEY-ID)
                aws configure set aws_secret_access_key $(AWS-SECRET-ACCESS-KEY)
                aws configure set default.region us-east-1

    - task: Bash@3
      displayName: Sonarcube placeholder
      inputs: 
        targetType: 'inline'
        script: |
                #! /bin/bash
                echo 'This will be a sonarqube analysis in the future'
    - task: Bash@3
      displayName: Push application image to ECR
      inputs:
        targetType: 'inline'
        script: |
                #! /bin/bash
                export db_username=$(db-username-test)
                export db_password=$(db-password-test)
                export db_endpoint=$(db-testing-endpoint)
                docker build -t testing .
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(ECR_URL_TESTING)
                docker tag testing $(ECR_URL_TESTING):$(Build.BuildNumber)
                docker push $(ECR_URL_TESTING):$(Build.BuildNumber)
                docker tag testing $(ECR_URL_TESTING):latest 
                docker push $(ECR_URL_TESTING):latest
    - task: Bash@3
      displayName: Unit tests placeholder
      inputs: 
        targetType: 'inline'
        script: |
                #! /bin/bash
                echo 'This will be a unittest slot in the future'

    - task: Bash@3
      displayName: Opening Pull request to dev branch
      inputs: 
        targetType: 'inline'
        script: |
                #! /bin/bash
                az repos pr create --repository Project-GL --source-branch $(Build.SourceBranchName) --target-branch dev-test --output table --auto-complete true
                echo 'Pull request created!'
      env:
        AZURE_DEVOPS_EXT_PAT: $(PAT)