---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: website
spec:
  containers:
  - name: website
    image: "$(ECR_URL_PRODUCTION)"
---
apiVersion: v1
kind: Service
metadata:
  name: testenv-deploy
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80