---
apiVersion: v1
kind: Pod
metadata:
  name: testenv
  labels:
    app: website
spec:
  containers:
  - name: website
    image: piotrowsianko/project:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
  - name: database
    image: postgres/postgres:14.4-alpine3.16
---
apiVersion: v1
kind: Service
metadata:
  name: testenv-deploy
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: database-deploy
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432