---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: website
spec:
  containers:
  - name: website
    image: "600831013510.dkr.ecr.us-east-1.amazonaws.com/production:latest"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: testenv-deploy
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http


